application:
  efgs:
    upload-diagnosis-keys:
      enabled: true
      simulate: false
      url: ${EFGS_WS_TECH}/upload
    download-diagnosis-keys:
      enabled: true
      download.url: ${EFGS_WS_TECH}/download
      audit.url: ${EFGS_WS_TECH}/audit/download
      simulate: false
    clean-batch-job:
      enabled: true
