server:
  ssl:
    enabled: false

application:
  efgs:
    upload-diagnosis-keys:
      simulate: true
      batching.cron: 0 */5 * * * ?
    download-diagnosis-keys:
      simulate: true
      batching.cron: 0 */5 * * * ?
