application:
  efgs:
    upload-diagnosis-keys:
      enabled: true
      simulate: false
      batching.cron: 0 */5 * * * ?
      url: ${EFGS_WS_TECH}/upload
    download-diagnosis-keys:
      enabled: true
      download.url: ${EFGS_WS_TECH}/download
      audit.url: ${EFGS_WS_TECH}/audit/download
      simulate: false
      batching.cron: 0 */5 * * * ?
    clean-batch-job:
      enabled: true
      batching.cron: 0 0 0 * * ?
