CREATE SEQUENCE SQ_NM_ID_BATCH_JOB_EXECUTION;
CREATE SEQUENCE SQ_NM_DOWNLOAD_EXECUTION;
CREATE SEQUENCE SQ_NM_UPLOAD_KEYS_EXECUTION;

CREATE TABLE BATCH_JOB_EXECUTION (
    NM_JOB_EXECUTION_ID INTEGER DEFAULT nextval('SQ_NM_ID_BATCH_JOB_EXECUTION'),
    DE_JOB_NAME         CHAR VARYING(64),
    FC_START_TIME       TIMESTAMP DEFAULT now(),
    FC_END_TIME         TIMESTAMP NULL,
    DE_STATUS           CHAR VARYING(10) DEFAULT 'STARTED',
    DE_MESSAGE          CHAR VARYING(256),
    CONSTRAINT PK_BATCH_JOB_EXECUTION
        PRIMARY KEY (NM_JOB_EXECUTION_ID)
);

CREATE TABLE DOWNLOAD_EXECUTION (
    NM_DOWNLOAD_ID      INTEGER DEFAULT nextval('SQ_NM_DOWNLOAD_EXECUTION'),
    NM_JOB_EXECUTION_ID INTEGER,
	FC_CREATED_AT		TIMESTAMP DEFAULT now(),
    FC_DOWNLOAD_DATE    TIMESTAMP,
	DE_BATCH_TAG		CHAR VARYING(64),
	DE_NEXT_BATCH_TAG	CHAR VARYING(64),
	DE_MESSAGE          CHAR VARYING(128),
    IN_SUCCESS          BOOLEAN DEFAULT FALSE,
    CONSTRAINT PK_DOWNLOAD_EXECUTION
        PRIMARY KEY (NM_DOWNLOAD_ID),
    CONSTRAINT FK_DOWNLOAD_BATCH_JOB
        FOREIGN KEY (NM_JOB_EXECUTION_ID)
            REFERENCES BATCH_JOB_EXECUTION (NM_JOB_EXECUTION_ID)
);

CREATE TABLE UPLOAD_KEYS_EXECUTION (
    NM_UPLOAD_KEYS_ID   INTEGER DEFAULT nextval('SQ_NM_UPLOAD_KEYS_EXECUTION'),
    NM_JOB_EXECUTION_ID INTEGER NOT NULL,
    FC_UPLOAD_DATE      TIMESTAMP DEFAULT now() NOT NULL,
    DE_BATCH_TAG        CHAR VARYING(64),
    DE_BATCH_SIGNATURE  CHAR VARYING(4096),
    DE_MESSAGE          CHAR VARYING(128),
    IN_SUCCESS          BOOLEAN DEFAULT FALSE,
    CONSTRAINT PK_UPLOAD_KEYS_EXECUTION
        PRIMARY KEY (NM_UPLOAD_KEYS_ID),
    CONSTRAINT UNQ_UPLOAD_KEYS_BATCH_TAG
        UNIQUE (DE_BATCH_TAG),
    CONSTRAINT FK_UPLOAD_KEYS_BATCH_JOB
        FOREIGN KEY (NM_JOB_EXECUTION_ID)
            REFERENCES BATCH_JOB_EXECUTION (NM_JOB_EXECUTION_ID)
);

ALTER SEQUENCE SQ_NM_ID_BATCH_JOB_EXECUTION
    OWNED BY BATCH_JOB_EXECUTION.NM_JOB_EXECUTION_ID;

ALTER SEQUENCE SQ_NM_DOWNLOAD_EXECUTION
    OWNED BY DOWNLOAD_EXECUTION.NM_DOWNLOAD_ID;

ALTER SEQUENCE SQ_NM_UPLOAD_KEYS_EXECUTION
    OWNED BY UPLOAD_KEYS_EXECUTION.NM_UPLOAD_KEYS_ID;

CREATE INDEX IN_EFGS_BATCH_JOB_EXECUTION_START_TIME
    ON BATCH_JOB_EXECUTION(FC_START_TIME);
	
CREATE INDEX IN_EFGS_DOWNLOAD_SUCCESS_DOWNLOAD_DATE_CREATED_AT
    ON DOWNLOAD_EXECUTION(IN_SUCCESS, FC_DOWNLOAD_DATE, FC_CREATED_AT);

CREATE INDEX IN_EFGS_DOWNLOAD_SUCCESS_DOWNLOAD_DATE_BATCH_TAG
    ON DOWNLOAD_EXECUTION(IN_SUCCESS, FC_DOWNLOAD_DATE, DE_BATCH_TAG);

CREATE INDEX IN_EFGS_UPLOAD_KEYS_SUCCESS
    ON UPLOAD_KEYS_EXECUTION(IN_SUCCESS);

CREATE INDEX IN_EFGS_UPLOAD_KEYS_BATCH_TAG
    ON UPLOAD_KEYS_EXECUTION(DE_BATCH_TAG);
